### ISSUE TITLE
issues 2.0.0

### ISSUE THREAD

**Issue by KubK0n** [Druidman/Serafin#11]
# database 
 - po wejściu wyświetlać ma się baza danych nie kategorie
 -  Nazwy kategorii według oryginału
 ## Usunąć kategorię:
  - "Cykle mszalne" 
 ## Zmienić nazwę kategorii: 
  - "Obrzędy Mszy świętej" na "Części stałe"
     ### dodać elementy
  - "Panie zmiłuj się nad nami", 
  - "Chwała na wysokości Bogu", 
  - "Święty, Święty, Święty",
  -  "Baranku Boży", 
  - "Ojcze nasz",
  -  "Wierzę w Boga (Credo)" oraz "Kyrie", 
  -  "Gloria",
  -  "Sanctus",
  -  "Agnus Dei",
  -  "Pater noster",
  -  "Credo" 
 ## Do kategorii adwent dodać wszystkie elementy które znajdują się w oryginale (przypomnij się o zdjęcia)

## Sortowanie alfabetyczne według polskich znaków
- resetowanie scrolla po wybraniu kategorii

# Format tekstu
- usunięcie każdego znaku `=` z tekstów
- dodanie numerów zwrotek
- dodanie refrenu po każdej zwrotce
- rozdzielić refren na osobny slajd
- uwzględnij że nie zawsze jest Ref. niekiedy pojawia się Ant.

## https://musicamsacram.pl/spiewnik/3125-otworz-sie-niebo-pokryte-chmurami
Tekst z tego linku powinien być pobrany

### To be continued...

**Comment by Druidman** [comment]
# **TO DO**


 # dodać elementy
  - "Panie zmiłuj się nad nami", 
  - "Chwała na wysokości Bogu", 
  - "Święty, Święty, Święty",
  -  "Baranku Boży", 
  - "Ojcze nasz",
  -  "Wierzę w Boga (Credo)" oraz "Kyrie", 
  -  "Gloria",
  -  "Sanctus",
  -  "Agnus Dei",
  -  "Pater noster",
  -  "Credo"
