### ISSUE TITLE
Wypierdol pan to przez okno

### ISSUE THREAD

**Issue by KubK0n** [Druidman/Serafin#12]
# ADWENT

## usuń
2. Boża mądrości, Ty...
3. Oto Panna pocznie i porodzi Syna [Msza roratnia]
4. O Gospodze uwielbiona (będzie dodane w jsonie z innym tytułem)
5. O miasto święte, Jeruzalem
6. Otwórz się niebo pokryte chmurami (to bez przecinka)
7. Pan jest blisko, już przychodzi by zbawienie ludziom dać
8. Raduj się, niebo, wesel się, ziemio (to z przecinkiem)
9. Zdrowaś Maryjo [Msza roratnia]

## schowek
2. Chwalmy Boga wszechmocnego
3. Czekamy Cię z tęsknotą serc
10. Cztery świece
11. Czuwajmy w gotowości, Bóg sam przyjdzie nas zbawić
12. Czysta Dziewico, Maryjo
13. Jak błyskawica znak Twój jaśnieje
14. Jasny Płomieniu miłości
15. Już dźwięczny głos się rozlega
16. Kiedyż przyjdzie Sprawiedliwy
17. Królestwo niebieskie, już ku nam się zbliża
18. Marana tha! Przybądź, Panie Jezu -- zmienić nazwę tego elementu na "Marana tha! Panie nasz przyjdź"
19. Matko Boża Adwentowa, chronisz
20. Na przyjście Chrystusa Króla
21. Niech będą przepasane biodra wasze
22. O Jutrzenko, zwiastujesz wschód Słońca
23. Posyła do Panny nie lada Anioła
24. Przyjdź Zbawicielu, przynieś nam światło
25. Przyjdź, Królu chwały, Emmanuelu
26. Przyjdź, Panie Jezu, tęsknie czekamy
27. Przyjdź, o Zbawicielu świata
28. Przyjdź, o Zbawienie pogańskie
29. Raduj się, niebo, wesel się ziemio
30. Raduj się, ziemio
31. Radujcie się zawsze w Panu
32. Radujcie się! Raz jeszcze powiem
33. (to musisz dodać ewentualnie skopiuj "Stwórco gwiaździstych przestworzy") Stwórco promiennych przestworzy
34. Szósta nadeszła godzina
35. Słowo zrodzone przed światłem
36. Tobie wznawiamy Panno
37. Wszyscy wierni śpiewajmy
38. Z pomocą Boga miłego
39. Z radością idziemy na spotkanie Pana

## przenieś
1. Creator alme... Do kategorii "Łacińskie"
2. Bliskie jest królestwo boże do "Wielki Post"
4. Ecce dominus veniet -- "Łacińskie"
5. Mittit ad Virginem -- "Łacińskie"
6. Rorate caeli -- "Łacińskie"
7. Veni, veni Emmanuel -- "Łacińskie"

**Comment by Druidman** [comment]
# wszystko usunięte
# wszystko przeniesione
# wszystko w schowku
