### ISSUE TITLE
Pieśni - obrazki

### ISSUE THREAD

**Issue by KubK0n** [Druidman/Serafin#13]
![image](https://github.com/user-attachments/assets/16e0d49c-0002-4c9d-a3da-bcbaf4d2dad8)
Mordo mówię ci dodajesz tu na drugi slajd coś takiego: Niebiosa rosę... Grzech nas oszpecił i w nędznej postaci * stoim przed Tobą, jakby trędowaci. oczywiście z numerkiem 2

![image](https://github.com/user-attachments/assets/c47267c6-7c1b-45c1-b570-00b9bd0a2cdd)
Mordo mówię ci wypierdzielasz stąd ze slajdu z refrenem wszystko co jest po albo włącznie ze słowem albo

![image](https://github.com/user-attachments/assets/2c58eeef-ef5d-43b0-bc5f-754ab915f318)
Usunąć zaznaczone (tak, całe te 2 slajdy wywalić wgl) i z tekstu na slajdach pousuwać '-' w słowach

![image](https://github.com/user-attachments/assets/c9390166-fc9e-4c1d-af9d-8b91e887a5b6)
Od słów "Przyjdź Panie wybaw nas" przenieść na kolejny slajd (łącznie z 2 zrobią się 4)

**Comment by Druidman** [comment]
# Wszystko zrobione
